import { ITrade } from "@/types/trade";

// sample trades data - expand/replace with your real API or DB data
const trades: ITrade[] = [
  {
    id: "1",
    title: "TSLA",
    pnl: 200,
    outcome: "Win",
    tradeType: "Long",
    entry: 500.0,
    exit: 300.0,
    date: new Date(),
  },
  {
    id: "2",
    title: "Price Action Analysis Trade",
    pnl: 0,
    outcome: "Not Taken",
    tradeType: "Short",
    entry: 500.0,
    exit: 300.0,
    date: new Date(),
  },
  {
    id: "3",
    title: "Price Action Analysis Trade",
    pnl: 200,
    outcome: "Win",
    tradeType: "Long",
    entry: 6881.61,
    exit: 6903.5,
    date: new Date(),
  },
  {
    id: "4",
    title: "Price Action Analysis Trade",
    pnl: 0,
    outcome: "Not Taken",
    tradeType: "Long",
    entry: 500.0,
    exit: 300.0,
    date: new Date(),
  },
  {
    id: "5",
    title: "Price Action Analysis Trade",
    pnl: -21.89,
    outcome: "Loss",
    tradeType: "Short",
    entry: 6881.61,
    exit: 6903.5,
    date: new Date(),
  },
  {
    id: "6",
    title: "Price Action Analysis Trade",
    pnl: -21.89,
    outcome: "Loss",
    tradeType: "Short",
    entry: 500.0,
    exit: 300.0,
    date: new Date(),
  },
  {
    id: "7",
    title: "Price Action Analysis Trade",
    pnl: -21.89,
    outcome: "Loss",
    tradeType: "Short",
    entry: 500.0,
    exit: 300.0,
    date: new Date(),
  },
  {
    id: "8",
    title: "Price Action Analysis Trade",
    pnl: -21.89,
    outcome: "Loss",
    tradeType: "Short",
    entry: 500.0,
    exit: 300.0,
    date: new Date(),
  },
  {
    id: "9",
    title: "Price Action Analysis Trade",
    pnl: -21.89,
    outcome: "Loss",
    tradeType: "Short",
    entry: 500.0,
    exit: 300.0,
    date: new Date(),
  },
  {
    id: "10",
    title: "Price Action Analysis Trade",
    pnl: -21.89,
    outcome: "Loss",
    tradeType: "Short",
    entry: 500.0,
    exit: 300.0,
    date: new Date(),
  },

  // add more rows to test pagination (duplicate entries for demo)
  {
    id: "11",
    title: "AAPL - Swing",
    pnl: 120.5,
    outcome: "Win",
    tradeType: "Long",
    entry: 145.0,
    exit: 150.5,
    date: new Date(),
  },
  {
    id: "12",
    title: "EURUSD Scalper",
    pnl: -35,
    outcome: "Loss",
    tradeType: "Short",
    entry: 1.18,
    exit: 1.1835,
    date: new Date(),
  },
  {
    id: "13",
    title: "GBPUSD - News",
    pnl: 0,
    outcome: "Not Taken",
    tradeType: "Long",
    entry: 1.3,
    exit: 1.298,
    date: new Date(),
  },
  {
    id: "14",
    title: "TSLA Re-entry",
    pnl: 45.0,
    outcome: "Win",
    tradeType: "Long",
    entry: 700.0,
    exit: 745.0,
    date: new Date(),
  },
  {
    id: "15",
    title: "Short Setup",
    pnl: -10.0,
    outcome: "Loss",
    tradeType: "Short",
    entry: 300.0,
    exit: 310.0,
    date: new Date(),
  },
  {
    id: "16",
    title: "Long Trend",
    pnl: 300,
    outcome: "Win",
    tradeType: "Long",
    entry: 1000.0,
    exit: 1300.0,
    date: new Date(),
  },
  {
    id: "17",
    title: "Fade the Rally",
    pnl: -5,
    outcome: "Loss",
    tradeType: "Short",
    entry: 420.0,
    exit: 425.0,
    date: new Date(),
  },
  {
    id: "18",
    title: "Reversal Setup",
    pnl: 40,
    outcome: "Win",
    tradeType: "Long",
    entry: 80.0,
    exit: 120.0,
    date: new Date(),
  },
  {
    id: "19",
    title: "Breakout",
    pnl: 15,
    outcome: "Win",
    tradeType: "Long",
    entry: 33.0,
    exit: 48.0,
    date: new Date(),
  },
  {
    id: "20",
    title: "Mean Reversion",
    pnl: -2,
    outcome: "Loss",
    tradeType: "Short",
    entry: 12.0,
    exit: 12.5,
    date: new Date(),
  },
];

export default trades;
