import { ITrade } from "@/types/trade";

const trades: ITrade[] = [
  {
    trade_id: "1",
    profit_loss: 200,
    outcome: "Win",
    trade_type: "Short",
    entry_price: 500.0,
    exit_price: 300.0,
    trade_date: new Date(),
  },
  {
    trade_id: "2",
    profit_loss: 0,
    outcome: "Not Taken",
    trade_type: "Long",
    entry_price: 500.0,
    exit_price: 300.0,
    trade_date: new Date(),
  },
  {
    trade_id: "3",
    profit_loss: 200,
    outcome: "Win",
    trade_type: "Long",
    entry_price: 6881.61,
    exit_price: 6903.5,
    trade_date: new Date(),
  },
  {
    trade_id: "4",
    profit_loss: 0,
    outcome: "Not Taken",
    trade_type: "Short",
    entry_price: 500.0,
    exit_price: 300.0,
    trade_date: new Date(),
  },
  {
    trade_id: "5",
    profit_loss: -21.89,
    outcome: "Loss",
    trade_type: "Long",
    entry_price: 6881.61,
    exit_price: 6903.5,
    trade_date: new Date(),
  },
  {
    trade_id: "6",
    profit_loss: -21.89,
    outcome: "Loss",
    trade_type: "Short",
    entry_price: 500.0,
    exit_price: 300.0,
    trade_date: new Date(),
  },
  {
    trade_id: "7",
    profit_loss: -21.89,
    outcome: "Loss",
    trade_type: "Short",
    entry_price: 500.0,
    exit_price: 300.0,
    trade_date: new Date(),
  },
  {
    trade_id: "8",
    profit_loss: -21.89,
    outcome: "Loss",
    trade_type: "Short",
    entry_price: 500.0,
    exit_price: 300.0,
    trade_date: new Date(),
  },
  {
    trade_id: "9",
    profit_loss: -21.89,
    outcome: "Loss",
    trade_type: "Short",
    entry_price: 500.0,
    exit_price: 300.0,
    trade_date: new Date(),
  },
  {
    trade_id: "10",
    profit_loss: -21.89,
    outcome: "Loss",
    trade_type: "Short",
    entry_price: 500.0,
    exit_price: 300.0,
    trade_date: new Date(),
  },
];

export default trades;
