import { ITrade } from "@/types/trade";

export const mockTrades: ITrade[] = Array.from({ length: 10 }).map((_, i) => ({
  id: `${i + 1}`,
  title: "Ascending Triangle - Daily",
  date: new Date("2025-10-31T12:00:00Z"),
  pnl: i % 2 === 0 ? 120 : -70,
  outcome: i % 2 === 0 ? "Win" : "Loss",
  type: "swing",
  tags: ["Daily", "Bullish", "Ascending Triangle"],
  image: "images/graph.png",
  signal: "BUY",
  value: 29,
}));

const trades: ITrade[] = [
  {
    id: "1",
    title: "TSLA",
    pnl: 200,
    outcome: "Win",
    type: "scalp",
    entry: 500.0,
    exit: 300.0,
    date: new Date(),
  },
  {
    id: "2",
    title: "Price Action Analysis Trade",
    pnl: 0,
    outcome: "Not Taken",
    type: "swing",
    entry: 500.0,
    exit: 300.0,
    date: new Date(),
  },
  {
    id: "3",
    title: "Price Action Analysis Trade",
    pnl: 200,
    outcome: "Win",
    type: "scalp",
    entry: 6881.61,
    exit: 6903.5,
    date: new Date(),
  },
  {
    id: "4",
    title: "Price Action Analysis Trade",
    pnl: 0,
    outcome: "Not Taken",
    type: "swing",
    entry: 500.0,
    exit: 300.0,
    date: new Date(),
  },
  {
    id: "5",
    title: "Price Action Analysis Trade",
    pnl: -21.89,
    outcome: "Loss",
    type: "swing",
    entry: 6881.61,
    exit: 6903.5,
    date: new Date(),
  },
  {
    id: "6",
    title: "Price Action Analysis Trade",
    pnl: -21.89,
    outcome: "Loss",
    type: "scalp",
    entry: 500.0,
    exit: 300.0,
    date: new Date(),
  },
  {
    id: "7",
    title: "Price Action Analysis Trade",
    pnl: -21.89,
    outcome: "Loss",
    type: "swing",
    entry: 500.0,
    exit: 300.0,
    date: new Date(),
  },
  {
    id: "8",
    title: "Price Action Analysis Trade",
    pnl: -21.89,
    outcome: "Loss",
    type: "swing",
    entry: 500.0,
    exit: 300.0,
    date: new Date(),
  },
  {
    id: "9",
    title: "Price Action Analysis Trade",
    pnl: -21.89,
    outcome: "Loss",
    type: "scalp",
    entry: 500.0,
    exit: 300.0,
    date: new Date(),
  },
  {
    id: "10",
    title: "Price Action Analysis Trade",
    pnl: -21.89,
    outcome: "Loss",
    type: "swing",
    entry: 500.0,
    exit: 300.0,
    date: new Date(),
  },
];

export default trades;
