import { UserType } from "@/types/user-types";

export const users: UserType[] = [
  {
    user_id: "1",
    email: "medamineabbes2@gmail.com",
    username: "medamineabbes",
    first_name: "Amine",
    last_name: "Abbes",
    avatar_url: "",
    timezone: "UTC",
    role: "user",
    status: "active",
    email_verified: false,
    created_at: new Date(),
    updated_at: new Date(),
    last_login: new Date(),
  },
  {
    user_id: "2",
    email: "medamineabbes@gmail.com",
    username: "amineabbes",
    first_name: "Amine",
    last_name: "Abbes",
    avatar_url: "",
    timezone: "UTC",
    role: "user",
    status: "suspended",
    email_verified: true,
    created_at: new Date(),
    updated_at: new Date(),
    last_login: new Date(),
  },
  {
    user_id: "3",
    email: "ammmzdfz@gmail.com",
    username: "some user name",
    first_name: "Amine",
    last_name: "Abbes",
    avatar_url: "",
    timezone: "UTC+1",
    role: "admin",
    status: "deleted",
    email_verified: true,
    created_at: new Date(),
    updated_at: new Date(),
    last_login: new Date(),
  },
  {
    user_id: "4",
    email: "medamin12344@gmail.com",
    username: "abbesmedamine",
    first_name: "Mohamed",
    last_name: "Mo5tar",
    avatar_url: "",
    timezone: "UTC",
    role: "user",
    status: "suspended",
    email_verified: false,
    created_at: new Date(),
    updated_at: new Date(),
    last_login: new Date(),
  },
];
